import { Workout, Student, ProgressData, Chat } from '@/types';

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    name: 'Treino de Peito e Tríceps',
    description: 'Foco em hipertrofia e força',
    duration: 60,
    difficulty: 'intermediate',
    category: 'Força',
    createdAt: '2025-10-28',
    exercises: [
      {
        id: 'e1',
        name: 'Supino Reto',
        sets: 4,
        reps: 12,
        weight: 80,
        rest: 90,
        notes: 'Manter controle na descida',
        completed: false,
      },
      {
        id: 'e2',
        name: 'Supino Inclinado',
        sets: 3,
        reps: 10,
        weight: 60,
        rest: 90,
        completed: false,
      },
      {
        id: 'e3',
        name: 'Crucifixo',
        sets: 3,
        reps: 15,
        weight: 20,
        rest: 60,
        completed: false,
      },
      {
        id: 'e4',
        name: 'Tríceps Testa',
        sets: 3,
        reps: 12,
        weight: 30,
        rest: 60,
        completed: false,
      },
      {
        id: 'e5',
        name: 'Tríceps Corda',
        sets: 3,
        reps: 15,
        rest: 60,
        completed: false,
      },
    ],
  },
  {
    id: '2',
    name: 'Treino de Costas e Bíceps',
    description: 'Desenvolvimento de massa muscular',
    duration: 65,
    difficulty: 'intermediate',
    category: 'Força',
    createdAt: '2025-10-29',
    exercises: [
      {
        id: 'e6',
        name: 'Barra Fixa',
        sets: 4,
        reps: 10,
        rest: 90,
        completed: false,
      },
      {
        id: 'e7',
        name: 'Remada Curvada',
        sets: 4,
        reps: 12,
        weight: 70,
        rest: 90,
        completed: false,
      },
      {
        id: 'e8',
        name: 'Puxada Frontal',
        sets: 3,
        reps: 12,
        weight: 60,
        rest: 60,
        completed: false,
      },
      {
        id: 'e9',
        name: 'Rosca Direta',
        sets: 3,
        reps: 12,
        weight: 30,
        rest: 60,
        completed: false,
      },
      {
        id: 'e10',
        name: 'Rosca Martelo',
        sets: 3,
        reps: 15,
        weight: 20,
        rest: 60,
        completed: false,
      },
    ],
  },
  {
    id: '3',
    name: 'Treino de Pernas',
    description: 'Treino completo de membros inferiores',
    duration: 70,
    difficulty: 'advanced',
    category: 'Força',
    createdAt: '2025-10-30',
    exercises: [
      {
        id: 'e11',
        name: 'Agachamento Livre',
        sets: 4,
        reps: 10,
        weight: 100,
        rest: 120,
        completed: false,
      },
      {
        id: 'e12',
        name: 'Leg Press',
        sets: 4,
        reps: 15,
        weight: 200,
        rest: 90,
        completed: false,
      },
      {
        id: 'e13',
        name: 'Cadeira Extensora',
        sets: 3,
        reps: 15,
        weight: 60,
        rest: 60,
        completed: false,
      },
      {
        id: 'e14',
        name: 'Mesa Flexora',
        sets: 3,
        reps: 12,
        weight: 50,
        rest: 60,
        completed: false,
      },
      {
        id: 'e15',
        name: 'Panturrilha em Pé',
        sets: 4,
        reps: 20,
        weight: 80,
        rest: 45,
        completed: false,
      },
    ],
  },
  {
    id: '4',
    name: 'HIIT Cardio',
    description: 'Treino intervalado de alta intensidade',
    duration: 30,
    difficulty: 'advanced',
    category: 'Cardio',
    createdAt: '2025-10-31',
    exercises: [
      {
        id: 'e16',
        name: 'Burpees',
        sets: 5,
        reps: 15,
        rest: 30,
        completed: false,
      },
      {
        id: 'e17',
        name: 'Mountain Climbers',
        sets: 5,
        duration: 45,
        rest: 30,
        completed: false,
      },
      {
        id: 'e18',
        name: 'Jump Squats',
        sets: 5,
        reps: 20,
        rest: 30,
        completed: false,
      },
      {
        id: 'e19',
        name: 'High Knees',
        sets: 5,
        duration: 45,
        rest: 30,
        completed: false,
      },
    ],
  },
];

export const mockStudents: Student[] = [
  {
    id: 's1',
    name: 'João Silva',
    email: 'joao@email.com',
    joinedAt: '2025-09-15',
    workoutsCompleted: 45,
    currentStreak: 7,
  },
  {
    id: 's2',
    name: 'Maria Santos',
    email: 'maria@email.com',
    joinedAt: '2025-08-20',
    workoutsCompleted: 62,
    currentStreak: 12,
  },
  {
    id: 's3',
    name: 'Pedro Costa',
    email: 'pedro@email.com',
    joinedAt: '2025-10-01',
    workoutsCompleted: 28,
    currentStreak: 5,
  },
  {
    id: 's4',
    name: 'Ana Oliveira',
    email: 'ana@email.com',
    joinedAt: '2025-07-10',
    workoutsCompleted: 89,
    currentStreak: 15,
  },
];

export const mockProgressData: ProgressData[] = [
  { date: '2025-10-01', workouts: 3, weight: 75 },
  { date: '2025-10-05', workouts: 4, weight: 74.5 },
  { date: '2025-10-10', workouts: 5, weight: 74 },
  { date: '2025-10-15', workouts: 4, weight: 73.8 },
  { date: '2025-10-20', workouts: 6, weight: 73.2 },
  { date: '2025-10-25', workouts: 5, weight: 72.8 },
  { date: '2025-10-31', workouts: 7, weight: 72.5 },
];

export const mockChats: Chat[] = [
  {
    id: 'c1',
    participantId: 's1',
    participantName: 'João Silva',
    lastMessage: 'Obrigado pelo treino de hoje!',
    lastMessageTime: '2025-10-31T10:30:00',
    unreadCount: 2,
    messages: [
      {
        id: 'm1',
        senderId: 's1',
        senderName: 'João Silva',
        text: 'Bom dia! Posso aumentar a carga no supino?',
        timestamp: '2025-10-31T09:00:00',
        read: true,
      },
      {
        id: 'm2',
        senderId: 'trainer',
        senderName: 'Personal Trainer',
        text: 'Bom dia! Sim, pode aumentar 5kg. Mantenha a técnica!',
        timestamp: '2025-10-31T09:15:00',
        read: true,
      },
      {
        id: 'm3',
        senderId: 's1',
        senderName: 'João Silva',
        text: 'Obrigado pelo treino de hoje!',
        timestamp: '2025-10-31T10:30:00',
        read: false,
      },
    ],
  },
  {
    id: 'c2',
    participantId: 's2',
    participantName: 'Maria Santos',
    lastMessage: 'Consegui bater meu recorde!',
    lastMessageTime: '2025-10-30T18:45:00',
    unreadCount: 1,
    messages: [
      {
        id: 'm4',
        senderId: 's2',
        senderName: 'Maria Santos',
        text: 'Consegui bater meu recorde!',
        timestamp: '2025-10-30T18:45:00',
        read: false,
      },
    ],
  },
];
